[package]
name = "test-fixtures"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
canonical-events = { path = "../canonical-events", version = "=0.1.0" }
domain-types = { path = "../domain-types", version = "=0.1.0" }
hex.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
toml.workspace = true

[dev-dependencies]
tempfile.workspace = true
