---
alpha_v1_services:
  - hl-analytics
  - hl-api
  - hl-capture
  - hl-core
  - hl-research

alpha_stage0_packages:
  - chrony
  - logrotate
  - openssh-server
  - sudo
  - ufw
  - unattended-upgrades

alpha_chrony_sources:
  - time.cloudflare.com
  - time.google.com
