[package]
name = "fixture-inspect"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
test-fixtures = { path = "../../crates/test-fixtures", version = "=0.1.0" }
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
